### PR TITLE
Add Connecticut scraper

### PR DESCRIPTION
**Pull request by AlbertUlysses**
adding Connecticut's pdf formatting python file for reproducibility.

### CODE REVIEW

**Comment by theswerd** [comment]
Can you create a folder, and add the pdf that this is based on?

**Comment by AlbertUlysses** [comment]
Okay, I just added the pdf folder and file.

**Comment by theswerd** [comment]
Sorry for the confusion, I meant add the pdf that this data is based on, so people can see where the data is coming from.

**Comment by AlbertUlysses** [comment]
That's what I did. 
I created a pdf folder that has the pdf file that the data is based on.

**Review by theswerd — APPROVED** [review]
So sorry -- I didn't see the PDF

LGTM

**Pull request merged**
